package com.traceledger.module.audit.enums;


public enum AuditAction {
    CREATED,
    UPDATED,
    DELETED,
    SHIPMENT_CREATED,
    SHIPMENT_DISPATCHED,
    SHIPMENT_RECEIVED,
    OWNERSHIP_TRANSFERRED,
    STATUS_CHANGED,
    SHIPMENT_DISPATCH_INITIATED,
    SHIPMENT_CANCELLED,
    SHIPMENT_MISSING,
    SHIPMENT_ITEM_MISSING,
    QUANTITY_MISMATCH,
    EXTRA_SHIPMENT_IN_DB,
    REPLAY_STARTED,
    REPLAY_COMPLETED
}

